version: '3'

services:
   db:
     container_name: ${CONTAINER_DB_NAME}
     image: mariadb:latest
     restart: unless-stopped
     volumes:
        - ${DB_PATH}:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   ghost:
     depends_on:
       - db
     container_name: ${CONTAINER_GHOST_NAME}
     image: ghost:latest
     restart: unless-stopped
     volumes:
       - ${GHOST_APPS}:/var/www/ghost/content/apps
       - ${GHOST_DATA}:/var/www/ghost/content/data
       - ${GHOST_IMAGES}:/var/www/ghost/content/images
       - ${GHOST_THEMES}:/var/www/ghost/content/themes
     environment:
       GHOST_DB_HOST: ${CONTAINER_DB_NAME}:3306
       GHOST_DB_NAME: ${MYSQL_DATABASE}
       GHOST_DB_USER: ${MYSQL_USER}
       GHOST_DB_PASSWORD: ${MYSQL_PASSWORD}
       VIRTUAL_HOST: ${DOMAINS}
       LETSENCRYPT_HOST: ${DOMAINS}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
       url: ${SITE_URL}
       NODE_ENV: ${STATUS}

networks:
    default:
       external:
         name: ${NETWORK}
