version: '3'

services:
   db:
     container_name: ${CONTAINER_DB_NAME}
     image: mariadb:10.2.14
     restart: unless-stopped
     volumes:
        - ${DB_PATH}:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   ghost:
     depends_on:
       - db
     container_name: ${CONTAINER_GHOST_NAME}
     image: ghost:1.22.2
     restart: unless-stopped
     volumes:
       - ${GHOST_APPS}:/var/www/ghost/content/apps
       - ${GHOST_DATA}:/var/www/ghost/content/data
       - ${GHOST_IMAGES}:/var/www/ghost/content/images
       - ${GHOST_THEMES}:/var/www/ghost/content/themes
     environment:
       url: ${SITE_URL}
       database__client: ${DATABASE_CLIENT}
       database__connection__host: ${CONTAINER_DB_NAME}:3306
       database__connection__database: ${MYSQL_DATABASE}
       database__connection__user: ${MYSQL_USER}
       database__connection__password: ${MYSQL_PASSWORD}
       NODE_ENV: ${STATUS}
       VIRTUAL_HOST: ${DOMAINS}
       LETSENCRYPT_HOST: ${DOMAINS}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

networks:
  default:
    external:
      name: ${NETWORK}
