version: '3'

services:
   db:
     container_name: ${CONTAINER_DB_NAME}
     image: mariadb:latest
     restart: unless-stopped
     volumes:
        - ${DB_PATH}:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}

   ghost:
     depends_on:
       - db
     container_name: ${CONTAINER_GHOST_NAME}
     image: ghost:latest
     restart: unless-stopped
     volumes:
       - ${GHOST_CORE}:/var/www/html
       - ${GHOST_CONTENT}:/var/www/html/ghost/content
     environment:
       GHOST_DB_HOST: ${CONTAINER_DB_NAME}:3306
       GHOST_DB_NAME: ${MYSQL_DATABASE}
       GHOST_DB_USER: ${MYSQL_USER}
       GHOST_DB_PASSWORD: ${MYSQL_PASSWORD}
       GHOST_TABLE_PREFIX: ${GHOST_TABLE_PREFIX}
       VIRTUAL_HOST: ${DOMAINS}
       LETSENCRYPT_HOST: ${DOMAINS}
       LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL} 

networks:
    default:
       external:
         name: ${NETWORK}
